module.exports={
    "collect polynomial exponents": "colleziona esponenti polinomiali!",
    "division by one": "Divisione per uno!",
    "collect constant exponents": "Colleziona esponenti costanti!",
    "add exponent of one": "Aggiungi l'esponente di uno!",
    "division by negative one": "Divisione per negativa!",
    "cancel terms": "Annulla i termini!",
    "break up fraction": "frazione di rottura!",
    "no change": "nessun cambiamento",
    "combine numerators": "Combina i numeratori!",
    "convert multiplication to exponent": "Converti la moltiplicazione in esponente!",
    "find gcd": "Trova GCD!",
    "group coefficients": "coefficienti di gruppo!",
    "rearrange coeff": "Riorganizzare Coeff!",
    "remove exponent by one": "rimuovere l'esponente da uno!",
    "remove multiplying by one": "rimuovere moltiplicando per uno!",
    "cancel exponent and root": "Annulla esponente e radice!",
    "combine under root": "Combina sotto la radice!",
    "multiply denominators": "moltiplicare i denominatori!",
    "multiply polynomial terms": "moltiplica i termini polinomiali!",
    "remove exponent base one": "Rimuovi l'esponente base uno!",
    "improper fraction numerator": "numeratore di frazione improprio!",
    "convert mixed number to improper fraction": "Converti il numero misto in frazione impropria!",
    "divide fraction for addition": "dividere la frazione per l'addizione!",
    "simplify terms": "Semplifica i termini!",
    "simplify fraction": "Semplifica la frazione!",
    "common denominator": "Denominatore comune",
    "convert integer to fraction": "Converti numeri interi in frazioni!",
    "simplify division": "Semplifica la divisione!",
    "collect and combine like terms": "Colleziona e combina termini simili!",
    "unary minus to negative one": "unario meno a quello negativo!",
    "add fractions": "Aggiungi frazioni!",
    "collect like terms": "Colleziona come termini!",
    "multiply by zero": "moltiplica per zero!",
    "add coefficient of one": "aggiungi il coefficiente di uno!",
    "expand exponent": "Espandi l'esponente!",
    "cancel gcd": "Annulla GCD!",
    "distribute": "diffondere un prospetto",
    "simplify arithmetic": "semplifica l'aritmetica!",
    "statement is true": "Questa affermazione è vera.",
    "divide from both sides": "dividere da entrambe le parti!",
    "add to both sides": "Aggiungi ad entrambi i lati!",
    "resolve double minus": "Risolvi il doppio meno!",
    "factor perfect square": "Fattore quadrato perfetto!",
    "break up term": "Termine di rottura!",
    "factor sum product rule": "Regola del prodotto di somma dei fattori!",
    "simplify signs": "Semplifica i segni!",
    "add nth roots": "Aggiungi le radici n-esime!",
    "multiply coefficients": "moltiplicare i coefficienti!",
    "nth root value": "n-esimo valore radice!",
    "multiply fractions": "moltiplicare le frazioni!",
    "multiply both sides by inverse fraction": "moltiplica entrambi i lati per la frazione inversa!",
    "distribute negative one": "distribuisci quello negativo!",
    "cancel root": "Annulla root!",
    "multiply by inverse": "moltiplica per l'inverso!",
    "simplify left side": "Semplifica il lato sinistro!",
    "cancel minuses": "Annulla gli svantaggi!",
    "multiply nth roots": "moltiplica le ennesime radici!",
    "multiply numerators": "moltiplicare i numeratori!",
    "reduce exponent by zero": "ridurre l'esponente di zero!",
    "find roots": "Trova le radici!",
    "remove multiplying by negative one": "rimuovere la moltiplicazione per quella negativa!",
    "remove adding zero": "rimuovere l'aggiunta di zero!",
    "subtract from both sides": "sottrarre da entrambi i lati!",
    "group terms by root": "Termini di gruppo per root!",
    "cancel exponent": "Annulla l'esponente!",
    "simplify right side": "Semplifica il lato destro!",
    "reduce zero numerator": "ridurre il numeratore zero!",
    "distribute nth root": "distribuire l'ennesima radice!",
    "factor symbol": "Simbolo del fattore!",
    "statement is false": "Questa affermazione è falsa.",
    "swap sides": "Scambia i lati!",
    "add polynomial terms": "Aggiungi termini polinomiali!",
    "multiply to both sides": "moltiplicatevi da entrambe le parti!",
    "multiply both sides by negative one": "Moltiplica entrambi i lati per uno negativo!",
    "factor into primes": "fattore in numeri primi!",
    "evaluate distributed nth root": "valutare l'ennesima radice distribuita!",
    "absolute value": "valore assoluto",
    "add numerators":"sommare i numeratori",
    "factor difference of squares":"differenza di fattore dei quadrati"
  }